add new functions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -330,6 +330,451 @@ $FULLDEBUG
 	fi
 	return 0
 }
+# Following the criterion required, building a config list function: findcfg
+
+function findcfg 
+{
+$FULLDEBUG
+
+	#
+	# Set default values
+	#
+
+	CFG_MACHINE=$SHORTHOSTNAME
+	USE_CFG_MACHINE="Y"
+	USE_CFG_USER="N"
+	CFG_GETLIST="N"
+	CFG_PRINT="N"
+	CFG_REVERSE="N"	
+
+	#
+	# Parse command line options
+	#
+
+	while getopts "MUlsprm:u:" opt
+	do
+        case $opt in
+       	         M)
+       	                 CFG_MACHINE=$SHORTHOSTNAME
+			 USE_CFG_MACHINE="Y"
+			 USE_CFG_USER="N";;
+       	         U)
+      	                 CFG_USER=`factory_id -un`
+			 USE_CFG_MACHINE="N"
+			 USE_CFG_USER="Y";;
+       	         s)
+       	                 CFG_GETLIST="N";;
+       	         p)
+       	                 CFG_PRINT="Y";;
+       	         m)      
+       	                 CFG_MACHINE=$OPTARG
+			 USE_CFG_MACHINE="Y"
+		         USE_CFG_USER="N";;
+       	         u)
+       	                 CFG_USER=$OPTARG
+			 USE_CFG_MACHINE="N"
+		  	 USE_CFG_USER="Y";;
+			 
+		 l) 
+			CFG_GETLIST="Y";;
+		 r)
+			CFG_REVERSE="Y";;
+                
+       	         \? )    usage
+                         exit 1 ;;
+       		 esac
+	done
+	shift $(($OPTIND - 1))
+
+	#OPTIND=1        #should be remove for SLES10 (need for cigwin)
+
+	filename=$1
+
+	#
+	# Save old FACTORY_CFGLIST
+	#
+
+	OLD_FACTORY_CFGLIST=$FACTORY_CFGLIST
+
+	#
+	# Build FACTORY_CFGLIST
+	#
+
+	if [ "$USE_CFG_MACHINE" = "Y" ]
+	then
+		FACTORY_CFGLIST=`machinecfglist $CFG_MACHINE`
+	fi
+
+	if [ "$USE_CFG_USER" = "Y" ]
+	then
+		FACTORY_CFGLIST=`usercfglist $CFG_USER`
+	fi
+
+	if [ "$CFG_REVERSE" = "Y" ]
+	then
+		tmplist=`reverse $FACTORY_CFGLIST`
+		FACTORY_CFGLIST=$tmplist
+	fi
+
+	
+	if [ "$CFG_GETLIST" = "N" ]
+	then
+		findcfgfile $filename
+		rc=$?
+	else
+		findcfglist $filename
+		rc=$?
+	fi
+
+	#
+	#  Reset FACTORY_CFGLIST
+	#
+
+	FACTORY_CFGLIST=$OLD_FACTORY_CFGLIST
+	return $rc
+
+}
+
+function machinecfglist 	# Get all standart Merck Serono configuration from the node function: machinecfglist
+{
+$FULLDEBUG
+	#
+	# For the moment hardcode config
+	# Next step : get from config file
+	# Next Next step : Get from config server (ldap for example)
+	#
+
+	#
+	# Backup FACTORY_<*> variables
+	#
+
+	PREV_FACTORY_ROLE="$FACTORY_ROLE"
+	PREV_FACTORY_MW="$FACTORY_MW"
+	PREV_FACTORY_ENV="$FACTORY_ENV"
+	PREV_FACTORY_ARCH="$FACTORY_ARCH"
+	PREV_FACTORY_DATACENTER="$FACTORY_DATACENTER"
+	PREV_FACTORY_LOCATION="$FACTORY_LOCATION"
+
+	MACHINE=$1
+	if [ -r $FACTORY_ROOT/attrcfg/etc/attributes.$MACHINE ]
+	then
+		. $FACTORY_ROOT/attrcfg/etc/attributes.$MACHINE
+	fi
+
+	#
+	# If FACTORY_LOCATION is no set in the attributes config file,
+	# FACTORY_LOCATION is the first 4 characters of the hostname 
+	#	deda,chge,....
+	#
+	if [ "$FACTORY_LOCATION" = "" ]
+	then
+		FACTORY_LOCATION=$(echo $MACHINE | cut -c1-4)
+	fi
+
+	#
+        # If FACTORY_ARCH is no set in the attributes config file,
+        # FACTORY_ARCH is the output of uname command.
+	# AIX , Linux , SunOS .....
+	#
+	if [ "$FACTORY_ARCH" = "" ]
+        then
+                FACTORY_ARCH=$(uname)
+        fi
+
+	OUTPUT="$MACHINE"
+
+        if [ "$FACTORY_ENV" != "" ]
+        then
+                if [ "$FACTORY_ROLE" != "" ]
+                then
+			if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                        	OUTPUT="$OUTPUT $FACTORY_ROLE$FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_ROLE$FACTORY_LOCATION$FACTORY_ENV $FACTORY_ROLE$FACTORY_CATEGORY $FACTORY_ROLE$FACTORY_ENV $FACTORY_ROLE$FACTORY_LOCATION $FACTORY_ROLE"
+                        else
+                        	OUTPUT="$OUTPUT $FACTORY_ROLE$FACTORY_LOCATION$FACTORY_ENV $FACTORY_ROLE$FACTORY_ENV $FACTORY_ROLE$FACTORY_LOCATION $FACTORY_ROLE"
+                        fi
+                fi
+
+                if [ "$FACTORY_MW" != "" ]
+                then
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$OUTPUT $FACTORY_MW$FACTORY_CATEGORY $FACTORY_MW$FACTORY_ENV $FACTORY_MW"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_MW$FACTORY_ENV $FACTORY_MW"
+                        fi
+                fi
+
+                if [ "$FACTORY_DATACENTER" != "" ]
+                then
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$OUTPUT $FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_ENV $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_ENV $FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_ENV $FACTORY_ARCH$FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_LOCATION"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_ENV $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_ENV $FACTORY_LOCATION$FACTORY_ENV $FACTORY_ARCH$FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_LOCATION"
+                        fi
+                else
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$FACTORY_LOCATION$FACTORY_ARCH$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_ENV $FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_ENV $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_ENV $FACTORY_LOCATION$FACTORY_ENV $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION"
+                        fi
+                fi
+
+		if [ "$FACTORY_CATEGORY" != "" ]
+		then
+                	OUTPUT="$OUTPUT $FACTORY_ARCH$FACTORY_CATEGORY $FACTORY_ARCH$FACTORY_ENV $FACTORY_ARCH $FACTORY_CATEGORY $FACTORY_ENV default"
+		else
+                	OUTPUT="$OUTPUT $FACTORY_ARCH$FACTORY_ENV $FACTORY_ARCH $FACTORY_ENV default"
+		fi
+        else
+                if [ "$FACTORY_ROLE" != "" ]
+                then
+			if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$OUTPUT $FACTORY_ROLE$FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_ROLE$FACTORY_CATEGORY $FACTORY_ROLE$FACTORY_LOCATION $FACTORY_ROLE"
+                        else
+                        	OUTPUT="$OUTPUT $FACTORY_ROLE$FACTORY_LOCATION $FACTORY_ROLE"
+                        fi
+                fi
+
+                if [ "$FACTORY_MW" != "" ]
+                then
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$OUTPUT $FACTORY_MW$FACTORY_CATEGORY $FACTORY_MW"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_MW"
+			fi
+                fi
+
+                if [ "$FACTORY_DATACENTER" != "" ]
+                then
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$OUTPUT $FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_ARCH$FACTORY_CATEGORY  $FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_ARCH$FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_LOCATION"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_ARCH$FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION$FACTORY_DATACENTER $FACTORY_LOCATION"
+                        fi
+                else
+                        if [ "$FACTORY_CATEGORY" != "" ]
+                        then
+                                OUTPUT="$FACTORY_LOCATION$FACTORY_ARCH$FACTORY_CATEGORY $FACTORY_LOCATION$FACTORY_CATEGORY $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION"
+                        else
+                                OUTPUT="$OUTPUT $FACTORY_ARCH$FACTORY_LOCATION $FACTORY_LOCATION"
+                        fi
+                fi
+
+		if [ "$FACTORY_CATEGORY" != "" ]
+		then
+                	OUTPUT="$OUTPUT $FACTORY_ARCH$FACTORY_CATEGORY $FACTORY_ARCH $FACTORY_CATEGORY default"
+		else
+                	OUTPUT="$OUTPUT $FACTORY_ARCH default"
+		fi
+        fi
+
+        echo $OUTPUT
+
+#	Order of criteria for configuration file search
+#	$MACHINE
+#	-$FACTORY_ROLE$FACTORY_LOCATION$FACTORY_CATEGORY
+#	--$FACTORY_ROLE$FACTORY_LOCATION$FACTORY_ENV
+#	---$FACTORY_ROLE$FACTORY_CATEGORY
+#	----$FACTORY_ROLE$FACTORY_ENV
+#	-----$FACTORY_ROLE$FACTORY_LOCATION
+#	------$FACTORY_ROLE
+#	-------$FACTORY_MW$FACTORY_CATEGORY
+#	--------$FACTORY_MW$FACTORY_ENV
+#	---------$FACTORY_MW
+#	----------$FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_CATEGORY
+#	-----------$FACTORY_LOCATION$FACTORY_DATACENTER$FACTORY_ENV
+#       ------------$FACTORY_LOCATION$FACTORY_ARCH$FACTORY_CATEGORY
+#       -------------$FACTORY_LOCATION$FACTORY_ARCH$FACTORY_ENV
+#	--------------$FACTORY_LOCATION$FACTORY_CATEGORY
+#	---------------$FACTORY_LOCATION$FACTORY_ENV
+#	----------------$FACTORY_ARCH$FACTORY_LOCATION$FACTORY_DATACENTER
+#	-----------------$FACTORY_ARCH$FACTORY_LOCATION
+#	------------------$FACTORY_LOCATION$FACTORY_DATACENTER
+#	-------------------$FACTORY_LOCATION 
+#	--------------------$FACTORY_ARCH$FACTORY_CATEGORY
+#	---------------------$FACTORY_ARCH$FACTORY_ENV
+#	----------------------$FACTORY_ARCH
+#       -----------------------$FACTORY_CATEGORY
+#	------------------------$FACTORY_ENV
+#	-------------------------default"
+
+	#
+	# Set back environment variables
+	#
+
+	FACTORY_ROLE="$PREV_FACTORY_ROLE"
+	FACTORY_MW="$PREV_FACTORY_MW"
+	FACTORY_ENV="$PREV_FACTORY_ENV"
+	FACTORY_ARCH="$PREV_FACTORY_ARCH"
+	FACTORY_DATACENTER="$PREV_FACTORY_DATACENTER"
+	FACTORY_LOCATION="$PREV_FACTORY_LOCATION"
+
+}
+# Show user configuration function: usercfglist
+
+function usercfglist
+{
+$FULLDEBUG
+	grplist=`factory_id -Gn $1`
+	echo "$1 $grplist default"
+}
+
+# 
+# Finding the configuration file function: findcfgfile
+function findcfgfile
+{
+$FULLDEBUG
+	$FULLDEBUG
+	filename=$1
+	for suffix in $FACTORY_CFGLIST
+	do
+		if [ -r $filename.$suffix ]
+		then 	
+			$ECHOCMD $filename.$suffix
+			return 0
+		fi
+	done
+	logwarn "No config file $filename.[$FACTORY_CFGLIST]"
+	return 1
+}
+
+function reverse
+{
+	list=$*
+	reverselist=""
+	for element in $list
+	do
+		reverselist="$element $reverselist"
+	done
+	echo $reverselist
+}
+
+# Finding the configuration list function: findcfglist
+
+function findcfglist
+{
+	$FULLDEBUG
+	filename=$1
+	found=""
+	for suffix in $FACTORY_CFGLIST
+	do
+		if [ -r $filename.$suffix ]
+		then 	
+			$ECHOCMD $filename.$suffix
+			found=1
+		fi
+	done
+	if [ -z "$found" ]
+	then
+		logerror "No config file $filename.[$FACTORY_CFGLIST]"
+		return 1
+	fi
+	return 0
+}
+
+# Sourcing the confuration file function: sourcecfgfile
+	
+function sourcecfgfile
+{
+	$FULLDEBUG
+	filelist=`findcfg -s $*`
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi
+	for fn in $filelist
+	do
+		if [ -r $fn ]
+		then 	
+			. $fn
+			return 0
+		fi
+	done
+	logerror "No config file for file $filelist"
+	return 1
+}
+
+# Sourcing the confuration list function: sourcecfglist
+
+function sourcecfglist
+{
+	$FULLDEBUG
+	filelist=`findcfg -l $*`
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi	
+	found=""
+	for fn in $filelist
+	do
+		if [ -r $fn ]
+		then 	
+			. $fn
+			found=1
+		fi
+	done
+	if [ -z "$found" ]
+	then
+		logerror "No config file $filelist"
+		return 1
+	fi
+	return 0
+}
+
+# Finding the configuration file and show it function: catcfgfile
+function catcfgfile
+{
+	$FULLDEBUG
+	filelist=`findcfg -s $*`
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi	
+	for fn in $filelist
+	do
+		if [ -r $fn ]
+		then 	
+			cat  $fn
+			return 0
+		fi
+	done
+	logerror "No config file $filelist"
+	return 1
+}
+
+# Finding the configuration list and show it function: catcfglist
+
+function catcfglist
+{
+	$FULLDEBUG
+	filelist=`findcfg -l $*`
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi
+	found=""
+	for fn in $filelist
+	do
+		if [ -r $fn ]
+		then 	
+			cat $fn
+			found=1
+		fi
+	done
+	if [ -z "$found" ]
+	then
+		logerror "No config file $filelist"
+		return 1
+	fi
+	return 0
+}
+
 
 # Setting the log environment function: setlogenv
 
@@ -366,6 +811,85 @@ function setlogenv
 		chmod a+w $FACTORY_LOGFILE
 	fi
 }
+#
+# Init part, run only once
+#
+	export FACTORY_PLATFORM=`uname`
+	case $FACTORY_PLATFORM in 
+		CYGWIN*)
+			export ECHOCMD="echo"
+			;;
+		Linux*)
+			export ECHOCMD="echo"
+			# Setup Linux distibution
+			if [ -r /etc/SuSE-release ]
+			then
+				export FACTORY_DISTRIB=Suse
+			elif [ -r /etc/redhat-release ]
+			then
+				export FACTORY_DISTRIB=RedHat
+			fi
+			;;
+		SunOS)
+			alias awk=/usr/xpg4/bin/awk
+			export ECHOCMD="print"
+			;;
+		*)
+			export ECHOCMD="print"
+			;;
+	esac
+
+if [[ -z "$FACTORY_CORE_FUNCTIONS" ]]
+then 
+	export HOSTNAME=`hostname`
+	export SHORTHOSTNAME=`echo $HOSTNAME | cut -f1 -d.`
+	#export FACTORY_LOCATION=`echo $SHORTHOSTNAME | cut -c1-3` # now it's set in attibute.hostanme config file
+	if [ -z "$PROGNAME" ]
+	then
+	  case $FACTORY_PLATFORM in
+		SunOS)	
+			export PROGNAME=`/usr/xpg4/bin/basesename -- $0`
+		;;
+		*)
+			export PROGNAME=`basename -- $0`
+		;;
+	  esac
+	fi
+
+	setlogenv
+	export FACTORY_TMPDIR=/var/factory/tmp
+	export FACTORY_TMPFILES=$FACTORY_TMPDIR/$PROGNAME.TEMFILES.$$
+
+	#export FACTORY_CFGLIST="$SHORTHOSTNAME default"
+	FACTORY_CFGLIST=`machinecfglist $SHORTHOSTNAME`
+	export FACTORY_CFGLIST
+	PATH=$PATH:$FACTORY_ROOT
+	export PATH
+
+	#
+	# Check tty
+	#
+
+	tty -s >/dev/null 2>/dev/null
+	if [ $? -ne 0 ]
+	then
+		FACTORY_NOTTY=1
+	fi
+	FACTORY_CORE_FUNCTIONS="DONE"
+	export FACTORY_NOTTY
+	export FACTORY_CORE_FUNCTIONS
+	if [ -f /usr/bin/sudo ]
+	then
+		FACTORY_SUDO=/usr/bin/sudo
+	elif [ -f /usr/local/bin/sudo ]
+	then
+		FACTORY_SUDO=/usr/local/bin/sudo
+	else
+		logerror "Can't find sudo command"
+		exit 1
+	fi
+	export FACTORY_SUDO
+fi
 
 function add_temp_files
 {
@@ -564,6 +1088,82 @@ $FULLDEBUG
         	The file does not exist
         	return 2
 	fi
+}
+
+# Function: headermenu
+#       - Display a simple header.
+#       - Use option 1 for title.
+#       - Use option 2 for display a current selection message.
+function headermenu {
+$FULLDEBUG
+        print
+        print "==========================================="
+        print "\t$1"
+        if [[ ! -z "$2" ]]
+        then
+                print " Current selection : $2"
+        fi
+        print "==========================================="
+        print
+}
+
+# Function: selectfctmenu
+#       - Simple function to display a menu using "select" command.
+#       - Display header before menu selection.
+#       - Remind current selection if used with option "S".
+function selectfctmenu {
+$FULLDEBUG
+	# set fix colums number to try to adap big menu list
+	export COLUMNS=155
+        clear
+        EXITOPT="Exit"
+        RETURNOPT=""
+        CURRENT_SELECTION=""
+	nshift=0
+        while getopts ":erS:" opt
+        do
+                case $opt in
+                        e)      EXITOPT=""
+                                nshift=`expr $nshift + 1 ` ;;
+                        r)      RETURNOPT="Return"
+                                nshift=`expr $nshift + 1 ` ;;
+                        S)      CURRENT_SELECTION="$OPTARG"
+                                nshift=`expr $nshift + 2 ` ;;
+                esac
+        done
+	shift $nshift
+        ALLFUNCTION="$*"
+        headermenu "$MENUNAME \n\tSelect option :" "$CURRENT_SELECTION"
+        select CHOICEFCT in $ALLFUNCTION $RETURNOPT $EXITOPT
+        do
+                if [[ -n "$CHOICEFCT" ]]
+                then
+                        if [[ "$CHOICEFCT" = "Exit" ]]
+                        then
+                                loginfo "Exit program requested by user."
+                                remove_temp_files
+                                exit 0
+                        elif [[ "$CHOICEFCT" = "Return" ]]
+                        then
+                                return
+                        else
+                                print "choice $CHOICEFCT"
+                                break
+                        fi
+                fi
+        done
+}
+
+# Function: press_return
+#       - Simple function to display a message and invite to press return to continue.
+function press_return
+{
+$FULLDEBUG
+echo "\n########################"
+echo "Press return to continue"
+echo "########################\n"
+read
+clear
 }
 
 # Function: list_to_line
@@ -824,6 +1424,32 @@ $FULLDEBUG
 		done
 		IFS=$IFS_BKP
 	done
+}
+
+# Function: detect_screen_size
+#       - Detect screen geometry
+#		. Set variable for Colums and Lines
+#		. Set variable for select command in function  of screen lines number
+function detect_screen_size
+{
+TTY_COLUMNS=$(stty -a | head -1 | awk -F ";" '{sub("columns","",$3);gsub (" ","",$3);print $3}')
+TTY_LINES=$(stty -a | head -1 | awk -F ";" '{sub("rows","",$2);gsub (" ","",$2);print $2}')
+SELECT_LINES=$(echo "${TTY_LINES} * 2 / 3" |bc)
+}
+
+# Function: set_screen_size
+#       - Set variables for tty
+#
+function set_screen_size
+{
+detect_screen_size
+export LINES=$TTY_LINES
+if [ $TTY_COLUMNS -gt 130 ]
+then
+	export COLUMNS=155
+else
+	export COLUMNS=130
+fi
 }
 
 # Function: convertsize
